language: python

python:
    - "2.7"
    - "3.3"

install:
    - pip install pytest-cov --use-mirrors
    - pip install pytest-pep8 --use-mirrors
    - pip install coveralls --use-mirrors

script: py.test test_envconfig.py --pep8 envconfig -v --cov envconfig --cov-report term-missing

after_success:
    - coveralls
