[tox]
envlist = py38, py39, py310, py311, py312, py313, lint
isolated_build = true

[testenv]
deps = pytest
commands = pytest -v

[testenv:lint]
deps =
    mypy
    ruff
commands =
    ruff check .
    ruff format --check .
    python -m mypy envconfig test_envconfig.py
